version: 2
jobs:
  node:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install

  android:
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout
      - run: npm install
      - run: bundle install
      - run: cd android && bundle exec fastlane test
      - run: cd android && bundle exec fastlane deploy_hockey

  ios:
    macos:
      xcode: "10.1"

    # use a --login shell so our "set Ruby version" command gets picked up for later steps
    shell: /bin/bash --login -o pipefail

    steps:
      - checkout
      - run: npm install
      - run: cd ios && bundle install
      - run: cd ios && bundle exec fastlane scan

workflows:
  version: 2
  node-android-ios:
    jobs:
      - node
      - android:
          requires:
            - node
      - ios:
          requires:
            - node
