# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :provisioning do
    produce(username: ENV["APPLE_ID"], app_identifier: 'com.wiprodigital.hellofromreactnative', app_name: 'HelloFromReactNative', skip_itc: true)
  end

  desc "Just another build"
  lane :build do
    get_certificates(username: ENV["APPLE_ID"])
    get_provisioning_profile(username: ENV["APPLE_ID"], app_identifier: 'com.wiprodigital.hellofromreactnative')
    build_app(scheme: "HelloJenkinsFromReactNative", clean: true)
  end
end
