# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :build do
    gradle(task: "clean assembleRelease")
  end

  desc "Build and deploy beta version to Hockey app"
  desc ""
  desc "Check https://docs.fastlane.tools/actions/hockey for a list of properties"
  lane :deploy_hockey do
    build
    hockey(
      api_token: ENV["HOCKEY_APP_TOKEN"],
      notes: "The official beta app"
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    build
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    build
    upload_to_play_store
  end
end
